sonar.projectKey=danielemontecchi_laravel-userstamps
sonar.organization=danielemontecchi
sonar.projectName=Laravel Userstamps
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**
sonar.exclusions=vendor/**
sonar.php.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
